### ISSUE TITLE
[BUG] <real_ip settings>

### ISSUE THREAD

**Issue by comfuzio** [linuxserver/docker-snapdrop#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, from the discord chat i am opening an issue here as requested
"hi, i want to ask for snapdrop it says on the guide "If you intend to expose Snapdrop to the internet, edit /config/nginx/site-confs/default.conf and uncomment the real_ip settings" but when i go to this file, it doesn't have anything with real_ip in it. I run it on ubuntu 22.10 with docker compose on portainer if that matters, is it in another file?"

Kind regards,
George

### Expected Behavior

To isolate the site to local sharing and not internet sharing

### Steps To Reproduce

Install docker compose
Install portainer
Deploy snapdrop as docker compose
make a domain in NPM and make it FQDN
visit that url from various locations and you will see all devices connected there instead of the local ones

### Environment

```markdown
- OS: Ubuntu 22.10 server
- How docker service was installed:
curl -fsSL https://get.docker.com/ -o get-docker.sh
chmod +x get-docker.sh
sh get-docker.sh
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
  snapdrop:
    image: lscr.io/linuxserver/snapdrop:latest
    container_name: snapdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - /opt/snapdrop:/config
    restart: unless-stopped
```

### Container logs

```bash
Logo
Home
local

Dashboard
App Templates

Stacks
Containers
Images
Networks
Volumes
Events
Host

Settings
Users

Environments

Registries
Licenses
Authentication logs

Notifications
Settings

©
Portainer Business Edition
2.17.0
Containers>snapdrop>Logs
Container logs


admin
Logs
Search...

Filter search results
Auto refresh
Fetch

All logs
Lines
1000

Show timestamp

Show line numbers

Wrap line
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
Setting resolver to  127.0.0.11
Setting worker_processes to 4
generating self-signed keys in /config/keys, you can replace these with your own keys if required
..........+........+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...........+.....+......+.+...+.....+.+.....+.+......+..+...+.......+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+.......................+.+..................+..+........................+.........+................+.....+............+....+...+.....+............+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
...+.........+..+....+.....+.........+.+.....+...+.+.................+...+....+..+.+............+.................+...+......+.......+...+..+.......+...+..+.+...........+.............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+...+.....+...+...+....+..+...+......+......+...+.......+...+..+.............+......+.....+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+...+..+...+.+.....+.+..............+.+...+......+...........+....+..+....+...+.................+......+.........+.+.................+..................+....+...+...........+.+........+.......+.....+.........+......+.+.....+............+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
[custom-init] No custom files found, skipping...
```

**Comment by nemchik** [comment]
Thanks for reporting this. I actually think our safest bet is to remove the mention of the `real_ip` configurations from the readme for this image. I do not think we should add the `real_ip` section back. There is no upstream (from snapdrop) documentation about this setting, so it was likely added by us at some point in the past. Recent internal discussions on the topic were cautious about including these settings by default more broadly.

I would recommend for now the best option is probably to use our CF real IP mod https://github.com/linuxserver/docker-mods/tree/swag-cloudflare-real-ip. Note that if you are using SWAG, this mod needs to be applied to SWAG as well as snapdrop (and any other nginx based container of ours that you need real IP reporting in).

**Comment by comfuzio** [comment]
No i do not use swag and i am not sure how to implement this to be honest. I am very new to docker and docker compose

**Comment by nemchik** [comment]
It is possible to expose this application via this container directly to the internet, but we advise using a reverse proxy such as https://github.com/linuxserver/docker-swag

With or without SWAG, what you need to do with the mod is add an environment variable to your snapdrop container with the name `DOCKER_MODS` and the value `linuxserver/mods:swag-cloudflare-real-ip` and follow the usage instructions section of the readme https://github.com/linuxserver/docker-mods/tree/swag-cloudflare-real-ip#mod-usage-instructions applying the changes to your nginx.conf inside your snapdrop config folder.

**Comment by comfuzio** [comment]
Bah, I removed it entirely!
Thanks for your time :)
