### ISSUE TITLE
additional settings for nginx reverse proxy

### ISSUE THREAD

**Issue by Hobbabobba** [linuxserver/docker-snapdrop#3]
to get the program working stable you need some settings for a (nginx) reverse proxy. maybe they are usefull for other users.

```
proxy_pass http://localhost:port;          # adjust ip instead of localhost and port
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
proxy_set_header Host $host;
proxy_set_header X-Forwarded-for $remote_addr;
```

**Comment by Erwyn** [comment]
Hi @Hobbabobba 

Did you change those settings in this docker container or did you change it on your reverse proxy in front of this container.

Cause i've seen that this image has a `FROM ghcr.io/linuxserver/baseimage-alpine-nginx:3.12` so it's unclear.

**Comment by Hobbabobba** [comment]
These are the settings for the external nginx reverse proxy.

**Comment by Erwyn** [comment]
so you managed to have one reverse proxy in front of the reverse proxy  already built in this image.

I'm trying this setup with a Caddy server but right now something might be wrong with the headers it's not working properly (seeing every connected device on the node independent of the network they're on).

**Comment by Erwyn** [comment]
From my understanding what you proposed is not enough as the embarked nginx proxy will override the incoming `X-Forwarded-For` header provided by the downstream server.

I just proposed a Pull request about this. 

If I'm wrong, do not hesitate to tell me.
