### ISSUE TITLE
Can't see other devices within subnet using provided docker-compose yml snippet

### ISSUE THREAD

**Issue by tamarindmonkey** [linuxserver/docker-snapdrop#7]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Be able to define specific external ports for the container and have devices be able to see each other when they have navigated to the snapdrop page.

## Current Behavior

Have never been able to see another device. I originally pulled this back at the beginning of 2021. The logs below are from the latest container pull after clearing the contents of the '/config' data locally. It doesn't matter if devices are both wired, wireless, or any combination thereof. There is absolutely nothing unusual or unique about the basic home network I'm trying to use this on. As others have noted, I can open a second browser or tab on the same host and see the additional 'device name' there and successfully send a file to the other instance of that device.

Also reported in discord here and a few other places: https://discord.com/channels/354974912613449730/506925392603512839/925594810075738134

## Steps to Reproduce

1. Install docker-ce, docker-compose, and all reqs as documented by official docker documentation
2. Use the compose snippet documented by this repo within its readme.md
3. Pull image and bring up container
4. Navigate to the defined http or https port at the external IP of the armv7l device running the container. (In my case this is 192.168.1.2)
5. snapdrop page should load fine and tell the user what its given "device name" is but no other devices are seen.

## Environment
**OS:** Raspberry Pi OS (uname -a: Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux)
**CPU architecture:** arm32
**How docker service was installed:** From the official repo, following the official instructions. Currently installed version of docker-ce: 5:20.10.12~3-0~raspbian-buster

## Command used to create docker container (run/create/compose/screenshot)

Using the same compose output as described in the readme.md save for my own port mapping:
```yaml
  snapdrop:
    image: ghcr.io/linuxserver/snapdrop
    container_name: snapdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/storage/docker/appdata/snapdrop:/config
    ports:
      - 8091:80
      - 8092:443
    restart: unless-stopped
```

## Docker logs

```
pi@raspberrypi:~ $ docker logs snapdrop
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
........................+++++
...+++++
writing new private key to '/config/keys/cert.key'
-----
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
[cont-init.d] 50-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Snapdrop is running on port 3000
pi@raspberrypi:~ $
```

**Comment by thespad** [comment]
This is unfortunately one of the limitations of Snapdrop - depending on the setup (local/proxied/internet) you have to make a number of config tweaks to get it working and there's no one size fits all solution we can provide out of the box.

Simplest fix for your case is to edit /config/nginx/site-confs/default and remove this line: https://github.com/linuxserver/docker-snapdrop/blob/master/root/defaults/default#L31 . Alternatively you can put Snapdrop behind a reverse proxy and that will achieve the same result.
