### ISSUE TITLE
Upgrade Required - nginx

### ISSUE THREAD

**Issue by nicosea** [linuxserver/docker-snapdrop#9]
I get the following error now:

_Upgrade Required!

The application inside this image has been moved to a new folder.

You will need to update your /config/nginx/nginx.conf and /config/nginx/site-confs/default.conf in order for the application to work.

New config samples are located at /config/nginx/nginx.conf.sample and /config/nginx/site-confs/default.conf.sample

Please review our announcement: [Significant changes to nginx based images](https://info.linuxserver.io/issues/2022-08-20-nginx-base/)_

**Comment by j0nnymoe** [comment]
It's telling you what to do.

**Comment by reejosam** [comment]
Trying to understand this change, why can't the new config.sample file be the default config in the docker image?

**Comment by Roxedus** [comment]
It is the new default, we just dont alter running instances

**Comment by ovizii** [comment]
> It's telling you what to do.

I found the new default files and simply replaced the old ones. All working again. Now need to compare them and see if I had touched any of the defaults.
